### PR TITLE
Update App Icons

### PR DESCRIPTION
**Pull request by TraumaD**
This:
g12

To This:
com github image-optimizer128
com github image-optimizer64
com github image-optimizer48
com github image-optimizer32
com github image-optimizer24
com github image-optimizer16

### CODE REVIEW

**Comment by TraumaD** [comment]
Actually I think I can mess with the colours a bit to better match your app's header colour. That could help tie it all together a little better.

**Comment by GijsGoudzwaard** [comment]
I really like the new icon set, could you update your pull request with the purple set? I think it fits the app more.

**Comment by TraumaD** [comment]
I'm going to try and get them updated today also I messed up the icon name and forgot your user in the RDNN. I'll fix that too.

**Comment by GijsGoudzwaard** [comment]
Look great, thanks!

**Pull request merged**
